#                  GSS
# ========================================
#
# This is the GSS config file.
# GSS needs the following to work properly

title: 'gss-test'
lang: 'it'
charset: 'utf-8'
theme: 'system' # Default theme is system. Choices are 'system', 'light' and 'dark' 

header_image: './assets/header.png'

short_description: 'this is a gss test'
long_description: |
  'this test is all about gss, which is a static website generator.'

author:
  name: 'John Doe'
  mail: 'johndoe@mail.com'
  phone: '+33611223344' # Don't forget international prefix
  github: 'https://github.com/Sonicfury'
  available_from: '9 AM'
  available_until: '7 PM'
  profile_picture: './assets/johndoe_face.png'

extras: # Documentation on https://github.com/trentm/python-markdown2/wiki/Extras
  - code-friendly
  - fenced-code_blocks
  - cuddled-lists
  - tables
  - footnotes

stylesheet: './assets/style.css'
javascript: '/assets/script.js'
md_path: './md_files'
html_path: './website'
