#                  Mastastigen!
# ========================================
#
# This is the Mastastigen! config file.
# Mastastigen! needs the following to work properly

title: 'Mastasigen!'
lang: 'en'
charset: 'utf-8'
theme: 'system' # Default theme is system. Choices are 'system', 'light' and 'dark'

header_image: './assets/img/kian-lem.jpg'

short_description: This is Mastastigen!, a Markdown Static Site Generator !
long_description: |
  This is Mastastigen!. Mastastigen! lets you generate a static website with just one command from markdown files !

  After you configure the projet in config.yaml, you can launch the script with the following command "python3 mastastigen.py".
  Just add "--help" or "-h" to get help. You can increase verbosity too with "--verbose" or "-v".

  This script is designed to be running on a server: the goal is to automate it with a cron so it will update your website every time you add a new markdown file.
  It is designed to generate a blog, where each markdown file becomes an article. In order for it to work properly, I recommend you begin your articles with a #title_1 ! You should understand why quickly !
author:
  name: 'John Doe'
  mail: 'johndoe@mail.com'
  phone: '+33611223344' # Don't forget international prefix
  github: 'https://github.com/Sonicfury'
  available_from: '9 AM'
  available_until: '7 PM'
  profile_picture: './assets/img/vicky-hladynets.jpg'

extras: # Documentation on https://github.com/trentm/python-markdown2/wiki/Extras
  - code-friendly
  - cuddled-lists
  - fenced-code-blocks
  - tables
  - footnotes
  - smarty-pants
  - numbering
  - tables
  - strike
  - spoiler

md_path: './md_files'
output: './www'

# Don't modify those unless you know what you're doing !
stylesheet: './assets/css/style.css'
javascript: './assets/js/script.js'
