#                  Mastasigen!
# ========================================
#
# This is the Mastasigen! config file.
# Mastasigen! needs the following to work properly

title: 'Mastasigen!'
lang: 'en'
charset: 'utf-8'
theme: 'system' # Default theme is system. Choices are 'system', 'light' and 'dark'

header_image: 'C:\Users\Utilisateur\Pictures\fall.jpg'

short_description: This is Mastasigen! demo site !
long_description: |
  This blog is a demo blog for my project Mastasigen!. This app is a Markdown static site generator. It's written in python (3.8) and SCSS mainly.

  Actually, two articles are available, a little personal note on the project (it has gifs so go read it) and a *.md test file with about everything you can do with GFM.

  Please note that this is a school project, It's my first python project and may or may not contain mistakes and design flaws. Be nice. Bye.
author:
  name: '0xJohnnyboy'
  mail: 'theo.lambert@viacesi.fr'
  phone: '+33644273556' # Don't forget international prefix
  github: 'https://github.com/0xJohnnyboy'
  available_from: '9 AM'
  available_until: '7 PM'
  profile_picture: 'C:\Users\Utilisateur\Pictures\face.png'

extras: # Documentation on https://github.com/trentm/python-markdown2/wiki/Extras
  - code-friendly
  - cuddled-lists
  - fenced-code-blocks
  - tables
  - footnotes
  - smarty-pants
  - numbering
  - tables
  - strike
  - spoiler

md_path: './md_files'
output: './docs'

# Don't modify those unless you know what you're doing !
stylesheet: './assets/css/style.css'
javascript: './assets/js/script.js'
